### ISSUE TITLE
Add Contributing.MD

### ISSUE THREAD

**Issue by kennym** [ZencashOfficial/HorizenAcademy#56]
This is a proposal to add a CONTRIBUTING.MD to make it easier for new people to contribute.

E.g.:
https://github.com/google/glog/blob/master/CONTRIBUTING.md

**Comment by jtoownus** [comment]
Good idea and thanks for the example!

**Comment by jtoownus** [comment]
PR is in. Feel free to take a look and give feedback @kennym
