### ISSUE TITLE
Add option to change the language in mobile version

### ISSUE THREAD

**Issue by jtoownus** [ZencashOfficial/HorizenAcademy#99]
**Feature Description**

Please add the option to change languages on the mobile version.

**Comment by jtoownus** [comment]
Any progress on this issue @tuanhvdev

**Comment by jtoownus** [comment]
By now you can add French and Spanish @tuanhvdev

**Comment by jtoownus** [comment]
Design of the new sidebar is provided [here](https://cdn.discordapp.com/attachments/508056130275246080/652466012364472346/Screenshot_2019-12-06_at_11.06.47.png)

Language Options should look like they do on our main website [(see here)](https://cdn.discordapp.com/attachments/508056130275246080/652467254184640528/Screenshot_2019-12-06_at_11.11.52.png)

**Comment by tuanhvdev** [comment]
I have added here: https://devweb-academy.horizen.global

**Comment by jtoownus** [comment]
Hey, generally looks good, but can you move both items ("See all Content" and language option) up a bit? On both, Chrome and Safari it is hidden behind the bottom status bar when opening the sidebar.
![image](https://user-images.githubusercontent.com/30371777/72600501-09840e80-3914-11ea-8a3f-717ff5582fc8.png)
 On Safari

![image](https://user-images.githubusercontent.com/30371777/72600531-1d2f7500-3914-11ea-8924-14a5f2c742e4.png)

On Chrome, both iPhone X
